# Patterns taken from the Sagemath source.
- name: 'python3: Python3 incompatible code'
  hint: |
    # ifilter, imap, izip           # __metaclass__
    Hint: # update raise statements       # except Exception, var
    Hint: # cmp                           # sagenb
    Hint: # next                          # six is no longer allowed
  pattern: '(import.*ifilter|import.*imap|import.*izip|^\s*raise\s*[A-Za-z]*Error\s*,|[\s,\(]cmp\s*=|[^_a-z]cmp\(|\.next\(\)|__metaclass__|except\s*[A-Za-z]\s*,|sagenb|import six|from six import)'
  filePattern: .*[.](py|pyx|rst)

- name: 'blocks: wrong syntax for blocks (INPUT, OUTPUT, EXAMPLES, NOTE, etc.)'
  hint: |
    # the correct syntax is .. SEEALSO::
    Hint: # TESTS and EXAMPLES should be plural, NOTE singular
    Hint: # no :: after INPUT, OUTPUT, REFERENCE blocks
    Hint: # no " :" at the end of lines
  pattern: '(\.\.SEE|SEE ALSO|SEEALSO:($|[^:])|^\s*TEST:|^\s*EXAMPLE:|^\s*NOTES:|^\s*[A-Z]*PUT::|^\s*REFERENCES?::$)'
